# Generated by Django 5.1.1 on 2024-12-22 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3a5e6cba-1d7f-42d9-8c17-55510d49590f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
