# Generated by Django 5.1.1 on 2024-12-22 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('97e6020f-ada1-48a2-997f-9d781833de44'), editable=False, primary_key=True, serialize=False),
        ),
    ]
