# Generated by Django 5.1.1 on 2024-12-20 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_uuid_alter_product_uuid_productimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('209cd187-4587-4641-bfe2-7d925fb7712a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('209cd187-4587-4641-bfe2-7d925fb7712a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('209cd187-4587-4641-bfe2-7d925fb7712a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
