# Generated by Django 5.1.1 on 2024-12-22 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_uuid_alter_product_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('1c2afa6e-5fc5-4def-922e-694f30b66082'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('color_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('1c2afa6e-5fc5-4def-922e-694f30b66082'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('size_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1c2afa6e-5fc5-4def-922e-694f30b66082'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1c2afa6e-5fc5-4def-922e-694f30b66082'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1c2afa6e-5fc5-4def-922e-694f30b66082'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='color_vaiant',
            field=models.ManyToManyField(to='products.colorvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_vaiant',
            field=models.ManyToManyField(to='products.sizevariant'),
        ),
    ]
