# Generated by Django 5.1.1 on 2024-12-22 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_colorvariant_sizevariant_alter_category_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_vaiant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_vaiant',
        ),
        migrations.AddField(
            model_name='product',
            name='color_variant',
            field=models.ManyToManyField(blank=True, to='products.colorvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_variant',
            field=models.ManyToManyField(blank=True, to='products.sizevariant'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3a5e6cba-1d7f-42d9-8c17-55510d49590f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3a5e6cba-1d7f-42d9-8c17-55510d49590f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3a5e6cba-1d7f-42d9-8c17-55510d49590f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3a5e6cba-1d7f-42d9-8c17-55510d49590f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3a5e6cba-1d7f-42d9-8c17-55510d49590f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
