# Generated by Django 5.1.1 on 2024-12-23 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_uuid_alter_colorvariant_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('b04cd282-b680-4588-b7be-0baf7af9ef48'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('coupon_code', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=100)),
                ('minimum_amount', models.IntegerField(default=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b04cd282-b680-4588-b7be-0baf7af9ef48'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b04cd282-b680-4588-b7be-0baf7af9ef48'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b04cd282-b680-4588-b7be-0baf7af9ef48'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b04cd282-b680-4588-b7be-0baf7af9ef48'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b04cd282-b680-4588-b7be-0baf7af9ef48'), editable=False, primary_key=True, serialize=False),
        ),
    ]
